BSS-54 :+ Add basic styling to the app
AND-Bootcamp/sunseeker-frontend pull request #4
Opened 2022-11-22 14:25 UTC by Jspek007

2022-11-22 14:31 UTC, hippalus approved these changes

2022-11-22 14:32 UTC, hippalus requested changes
confilict

2022-11-23 10:00 UTC, brunasti approved these changes

2022-11-23 16:13 UTC, nmimun approved these changes

2022-11-23 16:14 UTC, hippalus approved these changes

2022-11-24 08:46 UTC, closed without merging

2022-11-24 08:47 UTC, WidgetWolf commented
PR closed as it is being implemented in a different branch